"""Add payment_method to transactions

Revision ID: b326d2bc2ead
Revises: 20251122_add_market_selection_if_missing
Create Date: 2025-11-22 10:36:22.254402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b326d2bc2ead'
down_revision = '20251122_add_market_selection_if_missing'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
