"""Add Ticket and GamePick models

Revision ID: cfed9773af9b
Revises: 
Create Date: 2025-11-19 11:07:31.890643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfed9773af9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted for robustness ###
    # Update/normalize columns in `bets` table. If older DBs are missing
    # `market_type` or `selection` we'll add them instead of failing.
    with op.batch_alter_table('bets', schema=None) as batch_op:
        batch_op.alter_column(
            'id', existing_type=sa.INTEGER(), nullable=False, autoincrement=True
        )
        batch_op.alter_column(
            'amount', existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=False
        )
        batch_op.alter_column(
            'odds', existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=False
        )
        batch_op.alter_column(
            'potential_payout', existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=False
        )
        batch_op.alter_column(
            'bet_type', existing_type=sa.TEXT(), type_=sa.String(length=50), existing_nullable=False
        )

        bind = op.get_bind()
        insp = sa.inspect(bind)
        existing_cols = [c['name'] for c in insp.get_columns('bets')]

        if 'market_type' in existing_cols:
            batch_op.alter_column(
                'market_type', existing_type=sa.TEXT(), type_=sa.String(length=50), existing_nullable=True
            )
        else:
            batch_op.add_column(sa.Column('market_type', sa.String(length=50), nullable=True))

        if 'selection' in existing_cols:
            batch_op.alter_column(
                'selection', existing_type=sa.TEXT(), type_=sa.String(length=100), existing_nullable=True
            )
        else:
            batch_op.add_column(sa.Column('selection', sa.String(length=100), nullable=True))

        batch_op.alter_column(
            'status', existing_type=sa.TEXT(), type_=sa.String(length=20), existing_nullable=True, existing_server_default=sa.text("'pending'")
        )
        batch_op.alter_column(
            'result', existing_type=sa.TEXT(), type_=sa.String(length=20), existing_nullable=True
        )
        batch_op.alter_column(
            'settled_payout', existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True
        )
        batch_op.alter_column(
            'created_at', existing_type=sa.TEXT(), type_=sa.DateTime(), existing_nullable=True
        )
        batch_op.alter_column(
            'settled_at', existing_type=sa.TEXT(), type_=sa.DateTime(), existing_nullable=True
        )
        batch_op.alter_column(
            'expires_at', existing_type=sa.TEXT(), type_=sa.DateTime(), existing_nullable=True
        )

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('id', existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
        batch_op.alter_column('tx_hash', existing_type=sa.TEXT(), type_=sa.String(length=255), existing_nullable=False)
        batch_op.alter_column('amount', existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=False)
        batch_op.alter_column('transaction_type', existing_type=sa.TEXT(), type_=sa.String(length=20), existing_nullable=False)
        batch_op.alter_column('status', existing_type=sa.TEXT(), type_=sa.String(length=20), existing_nullable=True, existing_server_default=sa.text("'pending'"))
        batch_op.alter_column('from_address', existing_type=sa.TEXT(), type_=sa.String(length=255), existing_nullable=True)
        batch_op.alter_column('to_address', existing_type=sa.TEXT(), type_=sa.String(length=255), existing_nullable=True)
        batch_op.alter_column('fee', existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True, existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('created_at', existing_type=sa.TEXT(), type_=sa.DateTime(), existing_nullable=True)
        batch_op.alter_column('confirmed_at', existing_type=sa.TEXT(), type_=sa.DateTime(), existing_nullable=True)
        batch_op.create_foreign_key('fk_transactions_user_id_users', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id', existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
        batch_op.alter_column('username', existing_type=sa.TEXT(), type_=sa.String(length=80), existing_nullable=False)
        batch_op.alter_column('email', existing_type=sa.TEXT(), type_=sa.String(length=120), existing_nullable=False)
        batch_op.alter_column('password_hash', existing_type=sa.TEXT(), type_=sa.String(length=255), existing_nullable=False)
        batch_op.alter_column('balance', existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True, existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('created_at', existing_type=sa.TEXT(), type_=sa.DateTime(), existing_nullable=True)
        batch_op.alter_column('updated_at', existing_type=sa.TEXT(), type_=sa.DateTime(), existing_nullable=True)
        batch_op.alter_column('is_active', existing_type=sa.INTEGER(), type_=sa.Boolean(), existing_nullable=True, existing_server_default=sa.text('1'))

    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.alter_column('id', existing_type=sa.INTEGER(), nullable=False, autoincrement=True)
        batch_op.alter_column('bitcoin_address', existing_type=sa.TEXT(), type_=sa.String(length=255), existing_nullable=False)
        batch_op.alter_column('private_key_encrypted', existing_type=sa.TEXT(), type_=sa.String(length=255), existing_nullable=True)
        batch_op.alter_column('total_received', existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True, existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('total_sent', existing_type=sa.REAL(), type_=sa.Float(), existing_nullable=True, existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('created_at', existing_type=sa.TEXT(), type_=sa.DateTime(), existing_nullable=True)
        batch_op.alter_column('updated_at', existing_type=sa.TEXT(), type_=sa.DateTime(), existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('total_sent',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('total_received',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('private_key_encrypted',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('bitcoin_address',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('balance',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=80),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('confirmed_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('fee',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('to_address',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('from_address',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'"))
        batch_op.alter_column('transaction_type',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('tx_hash',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('bets', schema=None) as batch_op:
        batch_op.alter_column('expires_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('settled_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('settled_payout',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('result',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'"))
        batch_op.alter_column('selection',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('market_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('bet_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('potential_payout',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('odds',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('amount',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
